#spring.security.user:
#  name : surya
#  password : password
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_techie?createTableIfNotExists=true
    username: root
    password: "#InsanityHumanity1"
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    show-sql: true

server.port: 8080

#  spring.datasource.url=jdbc:mysql://localhost:3306/onlineshopping?createTableIfNotExists=true
#  spring.datasource.username=root
#  spring.datasource.password=#InsanityHumanity1
#
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql= true
#
#  spring.mvc.pathmatch.matching-strategy=ant-path-matcher